provisioner:
  # directory for the terraform binary
  terraform_dir: /tmp/tfbin
  # version of terraform to use
  terraform_version: 1.3.7
  # whether to overwrite the terraform binary silently
  overwrite: true
  # terraform provisioner backend
  backend:
    # 0 is used for local filesystem and 1 for s3 based storage
    provisioner_backend_type: 0
    # for local filesystem storage
    fs:
      root: /var/lib/gigo/provisioner/backend
    # for s3 based storage
    #s3:
    #  bucket: gigo-provisioner
    #  region: us-east-1
    #  access_key: access
    #  secret_key: secret
# storage for persisting terraform modules
module_storage:
  engine: fs
  fs:
    root: /var/lib/gigo/provisioner/modules
server:
  host: localhost
  port: 45246
logger:
  es:
    elastic_nodes:
      - NODE
    username: USER
    elastic_pass: PASS
    index: gigo-ws
    batch_size: 250
    batch_time_millis: 1000